### ISSUE TITLE
Issue with com_github_google_go_containerregistry

### ISSUE THREAD

**Issue by cotocisternas** [adobe/rules_gitops#67]
### Description of the problem / feature request:

fail to test with com_github_google_go_containerregistry digest error

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel test //...

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 4.0.0

### Snippet of the `WORKSPACE` file that includes rules_gitops rules.

```bazel
load("@com_adobe_rules_gitops//gitops:repositories.bzl", "rules_gitops_repositories")

rules_gitops_repositories()
```

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - Upstream issue: https://github.com/bazelbuild/rules_docker/issues/1139
> - Fix: https://github.com/cotocisternas/rules_gitops/tree/update-go-deps

**Comment by michaelschiff** [comment]
related change in rules_docker https://github.com/bazelbuild/rules_docker/commit/78f61b67da3aef1bd644af02fc81813a306928b6

**Comment by kzadorozhny** [comment]
As a workaround one can overwrite the `com_github_google_go_containerregistry` repository definition before  `rules_docker` and `gazelle` dependencies.

```python
load("@bazel_gazelle//:deps.bzl",  "go_repository")

# Overwrite external repository definition in the following container_go_dependencies call.
# Upstream tarbal sha256 has changed:
# from 3a5f9ff61b48b928ce37e9d227a581571957b3b3ad5d45d148bce5433f9c9a6c
# to   44ab9b4a959950922ca11f9fe511010f649c2af034dace12da37a33a4fae3ded
go_repository(
    name = "com_github_google_go_containerregistry",
    importpath = "github.com/google/go-containerregistry",
    sha256 = "44ab9b4a959950922ca11f9fe511010f649c2af034dace12da37a33a4fae3ded",
    strip_prefix = "google-go-containerregistry-e5f4efd",
    type = "tar.gz",
    urls = ["https://api.github.com/repos/google/go-containerregistry/tarball/e5f4efd48dbff3ab3165a944d6777f8db28f0ccb"],  # v0.1.2
)
```

**Comment by cotocisternas** [comment]
As a user of the library, @kzadorozhny workaround works great. In my case, I was trying to add support for gitlab in rules_gitops #68, and I found that most of the GO dependencies were out of date. When implementing this feature, I was forced to update go.mod to avoid transient dependency issues.
This branch https://github.com/cotocisternas/rules_gitops/tree/update-go-deps pass all the tests, but i'm not sure if it wold be ok to make a pull request, considering that basically all BUILD files in vendor were updated.

**Comment by kzadorozhny** [comment]
@cotocisternas, the dependency update looks reasonable. Feel free to open a PR. Ether separate one or in the scope of #68.

As for the `com_github_google_go_containerregistry` issue, we will bump `rules_docker` and `gazelle` dependency versions in the separate PR.
