### ISSUE TITLE
k8s deploy only tags images with latest

### ISSUE THREAD

**Issue by sdmichelini** [adobe/rules_gitops#74]
### Description of the problem / feature request:

> When pushing an image to a repo from k8s_deploy the only tag it support is latest

### Feature requests: what underlying problem are you trying to solve with this feature?

> Add user defined tags such as release versions to images.

**Comment by kzadorozhny** [comment]
I'm really hesitant to add this feature. Right now we don't push `latest` tag at all. The entire `rules_gitops` design is predicated on the premise of _avoiding_ tagging images. Tagging images is cumberstome in monorepo setting. In `rules_gitops` images are referenced in a content addressable manner. Which is a basis for how the `create_gitops_pr` tool works.

If workflow you are imagining requires manual image tagging, you can just use https://github.com/bazelbuild/rules_docker/blob/master/docs/container.md#container_push directly from the `rules_docker`

```python

container_image(
    name = "image",
    ...
)

container_push(
    name = "image.push",
    image = ":image",
    tag = "v1.0"  # don't forget to bump the tag on every relase 
    ...
)

```

**Comment by sdmichelini** [comment]
hi @kzadorozhny - that's not the behavior i am witnessing with the current implementation - currently we are seeing a log message like `Destination: acr.azurecr.io/{BUILD_USER}/appname:latest was resolved to acr.azurecr.io/{BUILD_USER}/appname:latest after stamping` - the template itself in .show still refers to the image by digest - in my use case it's very useful(especially in a mono-repo setting) to tie a digest back to what version of source code produced it. in terms of referencing the images - we always refer to via SHA.

**Comment by kzadorozhny** [comment]
The fact that the `latest` tag is still being pushed is a more of an oversight than an intended feature. In my opinion, adding a fixed image tag will add to the confusion about the intended use of `rules_gitops`.  I'm closing this ticket. Feel free to reach out in the [slack channel](https://bazelbuild.slack.com/archives/C01SF68MTFS) if you want to discuss any future.
